version: "3"

services:  
  vpn:
    image: ekristen/openvpn-client
    container_name: p592-openvpn
    stdin_open: true
    tty: true
    command: --config /trackerapi/config.ovpn --auth-nocache
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /home/ivan/projects/trackerapi:/trackerapi

  python:
    image: p592-python
    container_name: p592-python
    depends_on:
      - vpn
    network_mode: "service:vpn"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /home/ivan/Documents/projects/trackerapi:/Documents/projects/trackerapi
    build:
      context: .
      dockerfile: python.Dockerfile
    working_dir: /Documents/projects/trackerapi
    command: python control_server.py


